DROP TABLE IF EXISTS Camiseta;
DROP TABLE IF EXISTS Poster;

CREATE TABLE Camiseta(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    dorsal VARCHAR(255) NOT NULL,
    talla INT(10) NOT NULL,
    CONSTRAINT Camiseta_producto FOREIGN KEY (id) REFERENCES Producto(id) ON DELETE CASCADE
);

CREATE TABLE Poster(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    tamano INT(10) NOT NULL,
    CONSTRAINT Poster_producto FOREIGN KEY (id) REFERENCES Producto(id) ON DELETE CASCADE
);

