-- Tabla DIRECTOR (relacionada con EMPLEADO)
CREATE TABLE DIRECTOR (
    DNI VARCHAR(20) PRIMARY KEY,
    CARGO VARCHAR(50) DEFAULT 'DIRECTOR',
    FOREIGN KEY (DNI) REFERENCES EMPLEADO(DNI)
);

-- Tabla DEPENDIENTE (relacionada con EMPLEADO)
CREATE TABLE DEPENDIENTE (
	DNI VARCHAR(20) PRIMARY KEY,
    NUMVENTAS INT DEFAULT 0,
    FOREIGN KEY (DNI) REFERENCES EMPLEADO(DNI)
);