DROP TABLE IF EXISTS ENVIO;
DROP TABLE IF EXISTS ENTRADA;

CREATE TABLE ENVIO (
	ID VARCHAR(15) PRIMARY KEY,
    COSTE FLOAT NOT NULL,
    DIRECCION VARCHAR(50) NOT NULL,
    ESTADO VARCHAR(20) NOT NULL,
    FECHA_ENVIO DATE NOT NULL,
    FECHA_ENTREGA DATE
);
    
CREATE TABLE ENTRADA (
	ID VARCHAR(15) PRIMARY KEY,
    HORA VARCHAR(10) NOT NULL,
	FECHA DATE NOT NULL,
    UBICACION VARCHAR(20) NOT NULL,
    NUMERO_ASIENTO VARCHAR(5) NOT NULL,
    PARTIDO VARCHAR(20) NOT NULL,
    FOREIGN KEY (ID) REFERENCES PRODUCTO(ID)
);