CREATE TABLE VENTA (
    id INT AUTO_INCREMENT PRIMARY KEY,
    Precio FLOAT NOT NULL,
    Cantidad INT NOT NULL,
    IdProducto INT NOT NULL,
    FOREIGN KEY (IdProducto) REFERENCES producto(id) DELETE ON CASCADE UPDATE ON CASCADE
);

CREATE TABLE EMPLEADOS (
    identificador VARCHAR(20) PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    sueldo FLOAT NOT NULL
);